### ISSUE TITLE
Error when running truffle unbox optimism

### ISSUE THREAD

**Issue by timofeli** [truffle-box/optimism-box#21]
Hi, could you please point out if this is my misunderstanding or if something is causing this issue on your side?

Attaching the error message. 

```
$ truffle unbox optimism
This directory is non-empty...
? Proceed anyway? (Y/n) 
Starting unbox...
=================

? Proceed anyway? Yes
✓ Preparing to download box
✓ Downloading
npm ERR! code ERR_INVALID_ARG_TYPE
npm ERR! The "from" argument must be of type string. Received undefined

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/eli/.npm/_logs/2022-05-23T20_37_05_269Z-debug-0.log
✓ Cleaning up temporary files
✖ Setting up box
Unbox failed!
Error: Command failed: npm install --loglevel=error && touch .env
npm ERR! code ERR_INVALID_ARG_TYPE
npm ERR! The "from" argument must be of type string. Received undefined

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/eli/.npm/_logs/2022-05-23T20_37_05_269Z-debug-0.log

    at checkExecSyncError (node:child_process:828:11)
    at Object.execSync (node:child_process:899:15)
    at Object.installBoxDependencies (/usr/local/lib/node_modules/truffle/build/webpack:/packages/box/dist/lib/utils/unbox.js:139:1)
    at Object.setUpBox (/usr/local/lib/node_modules/truffle/build/webpack:/packages/box/dist/lib/utils/index.js:52:1)
    at /usr/local/lib/node_modules/truffle/build/webpack:/packages/box/dist/box.js:183:1
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/node_modules/truffle/build/webpack:/packages/box/dist/box.js:5:43)
Truffle v5.5.15 (core: 5.5.15)
Node v16.15.0

```

**Comment by fainashalts** [comment]
Hi @timofeli thanks for reaching out! I see in your output that you are unboxing into a non-empty directory. When I attempt the command in an empty directory everything appears to work as expected. Can you try this in an empty directory and let me know if it works? Thanks!

**Comment by timofeli** [comment]
@fainashalts Thank you for your prompt reply!
I just did it and had the same error. 

`eli@eli-XPS-13-9360:~/test2$  truffle unbox optimism

Starting unbox...
=================

✓ Preparing to download box
✓ Downloading
npm ERR! code ERR_INVALID_ARG_TYPE
npm ERR! The "from" argument must be of type string. Received undefined

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/eli/.npm/_logs/2022-05-24T06_30_31_985Z-debug-0.log
✓ Cleaning up temporary files
✖ Setting up box
Unbox failed!
Error: Command failed: npm install --loglevel=error && touch .env
npm ERR! code ERR_INVALID_ARG_TYPE
npm ERR! The "from" argument must be of type string. Received undefined

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/eli/.npm/_logs/2022-05-24T06_30_31_985Z-debug-0.log

    at checkExecSyncError (node:child_process:828:11)
    at Object.execSync (node:child_process:899:15)
    at Object.installBoxDependencies (/usr/local/lib/node_modules/truffle/build/webpack:/packages/box/dist/lib/utils/unbox.js:139:1)
    at Object.setUpBox (/usr/local/lib/node_modules/truffle/build/webpack:/packages/box/dist/lib/utils/index.js:52:1)
    at /usr/local/lib/node_modules/truffle/build/webpack:/packages/box/dist/box.js:183:1
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/node_modules/truffle/build/webpack:/packages/box/dist/box.js:5:43)
Truffle v5.5.15 (core: 5.5.15)
Node v16.15.0
`

**Comment by beakerfm** [comment]
Seems to be an issue with the version of node and changes between major versions.  I received same error as @timofeli when using node v17.4.0. Seems they are using 16.15.0 when testing above. When downgrading to a lower version of node 12.22.12 the unbox worked successfully.  I removed the `node_modules` directory from this repo to allow the post install script to execute and it seems to work as intended.  Here is open PR with the change to fix this issue: https://github.com/truffle-box/optimism-box/pull/25

**Comment by beakerfm** [comment]
@timofeli your issue should now be resolved as https://github.com/truffle-box/optimism-box/pull/26 is merged with the fix.

**Comment by fainashalts** [comment]
Hello @timofeli so sorry I lost track of this. Looks like @beakerfm was able to help get this resolved. I'm going to close this issue but please feel free to open a fresh one if you encounter any other issues! Thanks!
